### ISSUE TITLE
How to add own templates?

### ISSUE THREAD

**Issue by trenkert** [niebert/PanDocElectron#1]
I'd like to add my own LaTeX and ConTeXt templates to Pandocelectron. How can I do this?

**Comment by niebert** [comment]
When you install PanDocElectron there is also a PanDoc directory checked out 
see https://github.com/niebert/PanDoc . The LaTeX templates can be found in the subdirectory tpl/  (see https://github.com/niebert/PanDoc/tree/master/tpl ). The default templates of PanDoc written by John McFarlane are  stored in the tpl/pandoctemplates/ . If you run PanDocElectron it creates for you a shell script ___callpandoc.sh___ on Mac/Linux and ___callpandoc.bat___ on Windows in documents directory tailored for your PanDoc generation. Rename the ___callpandoc.sh___ e.g. ___mytemplatepandoc.sh___ and alter the -template parameter to a template you want to use.

      --template=/Users/myname/Documents/PanDoc/tpl/reveal/mytemplate.html 

  ___mytemplatepandoc.sh___ will generate the documuents with your defined template.

I take that as recommendation to template selection for other formats in the GUI of PanDoc Electron.
I hope that workaround helps you for now.
regards Bert

**Comment by niebert** [comment]
General Template Folder can be set in settings
